### ISSUE TITLE
Stream parsing

### ISSUE THREAD

**Issue by chenglou** [chenglou/BetterErrors#30]
Showing the whole result only at the end is not scalable for larger apps.

**Comment by jordwalke** [comment]
I suggest inserting "flush" strings in the output of `jengaboot` and merging the two projects. This way you can wrap each compilation command with `<command>`..`</command>`. Otherwise if you don't merge the two projects you could just say that `BetterErrors` will stream consecutively whenever seeing certain wrapping tags (you can turn this feature on/off).

**Comment by chenglou** [comment]
Shit's streaming now!
The thing I catch is "File ..., line 2...:". This is good enough for now.

**Comment by jordwalke** [comment]
Great!
